<?php
	require_once($projectDir.'Routes/event.php');
	require_once($projectDir.'Routes/events.php');
	require_once($projectDir.'Routes/calls.php');
	require_once($projectDir.'Routes/user.php');
	require_once($projectDir.'Routes/users.php');
	require_once($projectDir.'Routes/friendships.php');
	require_once($projectDir.'Routes/followers.php');
	require_once($projectDir.'Routes/friends.php');
?>